<%@ Page Title="Список книг" Language="C#" MasterPageFile="~/Site.Master" 
    AutoEventWireup="true" CodeBehind="BooksList.aspx.cs" 
    Inherits="BookLibraryWF.Pages.BooksList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container mt-4">
        <h2>Список книг</h2>
        
        <asp:Button ID="btnAddNew" runat="server" Text="+ Добавить книгу" 
            OnClick="btnAddNew_Click" CssClass="btn btn-success mb-3" />
            
        <div class="table-responsive">
            <asp:GridView ID="gvBooks" runat="server" 
                AutoGenerateColumns="False"
                DataKeyNames="Id"
                CssClass="table table-hover"
                OnRowCommand="gvBooks_RowCommand"
                AutoGenerateDeleteButton="false">
                
                <Columns>
                    <asp:BoundField DataField="Title" HeaderText="Название" />
                    <asp:BoundField DataField="Author" HeaderText="Автор" />
                    <asp:BoundField DataField="PublishYear" HeaderText="Год" />
                    
                    <asp:TemplateField HeaderText="Действия" ItemStyle-Width="250px" ItemStyle-HorizontalAlign="Center">
                        <ItemTemplate>
                            <!-- Кнопка Просмотр -->
                            <asp:Button ID="btnView" runat="server" Text="Просмотр" 
                                CommandName="View" 
                                CommandArgument='<%# Eval("Id") %>'
                                CssClass="btn btn-info btn-sm" />
                                
                            <!-- Кнопка Редактировать -->
                            <asp:Button ID="btnEdit" runat="server" Text="Редактировать" 
                                CommandName="Edit" 
                                CommandArgument='<%# Eval("Id") %>'
                                CssClass="btn btn-primary btn-sm" />
                                
                            <!-- Кнопка Удалить -->
                            <asp:Button ID="btnDelete" runat="server" Text="Удалить" 
                                CommandName="CustomDelete" 
                                CommandArgument='<%# Eval("Id") %>'
                                CssClass="btn btn-danger btn-sm"
                                OnClientClick="return confirm('Вы точно хотите удалить эту книгу?');" />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>